package com.oteo.core.util;

public enum CsvFile {

	COMPANY,
	ORGANIZATION,
	ACTIVITY_ORGANIZATION,
	ENVIRONMENTAL_CONFLICT,
	ENVIRONMENTAL_CONFLICT_COMPANY,
	ENVIRONMENTAL_CONFLICT_ORGANIZATION,
	DEFENDER,
	ORGANIZATION_DEFENDER,
	DEFENDER_CASE_TRACKING,
	HUMAN_RIGHT_VIOLATION,
	LEGISLATION;

}
